#!/bin/bash
# 🚀 VANTRACK - QUICK START SCRIPT

echo "╔════════════════════════════════════════════════════════════╗"
echo "║           VANTRACK - QUICK START                          ║"
echo "║        MySQL Integration Complete ✅                     ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""

# Cores
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${BLUE}📋 PRÉ-REQUISITOS:${NC}"
echo "   • Python 3.8+"
echo "   • MySQL Server 8.0+"
echo "   • Git"
echo ""

echo -e "${BLUE}📁 ESTRUTURA DO PROJETO:${NC}"
echo "   Projeto-vantrack/"
echo "   ├── backend/                    # Flask + Socket.IO"
echo "   │   ├── app.py                  # Aplicação principal"
echo "   │   ├── database.py             # MySQL Connection Pool"
echo "   │   ├── setup_database.py       # Setup do banco"
echo "   │   ├── requirements.txt        # Dependências"
echo "   │   ├── test_complete_flow.py   # Testes completos"
echo "   │   └── ...                     # Rotas, Use Cases, Infra"
echo "   ├── database/                   # Schema SQL"
echo "   │   └── schema.sql              # 10 Tabelas MySQL"
echo "   ├── .env                        # Configurações"
echo "   ├── TESTING.md                  # Guia de Testes"
echo "   ├── IMPLEMENTATION.md           # Status da Implementação"
echo "   └── README.md                   # Documentação"
echo ""

echo -e "${BLUE}🚀 INICIANDO:${NC}"
echo ""
echo "1️⃣  Ativar Virtual Environment:"
echo "    ${YELLOW}cd Projeto-vantrack${NC}"
echo "    ${YELLOW}.venv\\Scripts\\activate${NC} (Windows)"
echo "    ${YELLOW}source .venv/bin/activate${NC} (Linux/Mac)"
echo ""

echo "2️⃣  Instalar Dependências:"
echo "    ${YELLOW}pip install -r backend/requirements.txt${NC}"
echo ""

echo "3️⃣  Setup do Banco de Dados:"
echo "    ${YELLOW}cd backend${NC}"
echo "    ${YELLOW}python setup_database.py${NC}"
echo ""

echo "4️⃣  Iniciar Servidor:"
echo "    ${YELLOW}python app.py${NC}"
echo "    → Rodando em http://localhost:5000"
echo ""

echo "5️⃣  Em outro terminal, rodar testes:"
echo "    ${YELLOW}python test_complete_flow.py${NC}"
echo ""

echo -e "${GREEN}✅ STATUS ATUAL:${NC}"
echo "   ✓ MySQL Backend Funcionando"
echo "   ✓ Autenticação JWT Implementada"
echo "   ✓ 10 Tabelas Criadas"
echo "   ✓ Conexão Pool Ativa"
echo "   ✓ Testes Passando"
echo ""

echo -e "${BLUE}📊 ENDPOINTS DISPONÍVEIS:${NC}"
echo ""
echo "   PUBLIC:"
echo "   • POST   /api/cadastro              Cadastrar usuário"
echo "   • POST   /api/login                 Fazer login"
echo "   • POST   /api/recuperar-senha       Recuperar senha"
echo ""
echo "   PROTECTED (requer JWT):"
echo "   • GET    /api/perfil                Perfil do usuário"
echo "   • GET    /api/usuarios              Lista de usuários"
echo "   • GET    /api/rotas                 Lista de rotas"
echo "   • POST   /api/rotas                 Criar rota"
echo "   • GET    /api/veiculos              Lista de veículos"
echo "   • POST   /api/veiculos              Criar veículo"
echo ""

echo -e "${BLUE}🧪 TESTES:${NC}"
echo ""
echo "   Fluxo Completo:"
echo "   ${YELLOW}python test_complete_flow.py${NC}"
echo ""
echo "   Apenas Setup do Banco:"
echo "   ${YELLOW}python setup_database.py${NC}"
echo ""
echo "   Verificar Dados:"
echo "   ${YELLOW}python check_db.py${NC}"
echo ""

echo -e "${BLUE}🔑 CREDENCIAIS PADRÃO:${NC}"
echo "   Database: localhost:3306"
echo "   User: root"
echo "   Database: vantrack"
echo "   (Verifique .env para customização)"
echo ""

echo -e "${BLUE}📚 DOCUMENTAÇÃO:${NC}"
echo "   • TESTING.md        → Guia completo de testes"
echo "   • IMPLEMENTATION.md → Status da implementação"
echo "   • PROJECT.md        → Especificações do projeto"
echo "   • CLAUDE.md         → Histórico de implementação"
echo ""

echo -e "${GREEN}═══════════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}   🎉 PRONTO PARA USAR! 🎉${NC}"
echo -e "${GREEN}═══════════════════════════════════════════════════════════${NC}"
echo ""
